### ISSUE TITLE
igvm-v0.1.6 tag missing

### ISSUE THREAD

**Issue by stefano-garzarella** [microsoft/igvm#35]
It looks like commit 44708fda9a8ddc72e1ef7993c020bc4c1fc12a8d produced a release (which is also pushed on crates.io: https://crates.io/crates/igvm/0.1.6), but there isn't the tag pushed in this repository.

**Comment by chris-oo** [comment]
Interesting, I usually use `cargo release` https://github.com/crate-ci/cargo-release to generate releases which is supposed to push tags to the repo automatically. I'll fixup this one and keep an eye out for next time. 

I'm really hoping that soon I don't have to manually spin releases and we can do it via a GH pipeline but more research on my side is needed.

**Comment by chris-oo** [comment]
I've fixed up the v0.1.6 release manually, and I'll keep this open to look at the next release as well. Thanks for the report!

**Comment by stefano-garzarella** [comment]
ooo, I didn't know about `cargo release` I'll also check that since in rust-vmm we are doing this step manually. Thanks for sharing!

**Comment by chris-oo** [comment]
Yeah it's a neat tool. I think someone from the Microsoft Rust team found it and it's been pretty useful.

**Comment by chris-oo** [comment]
Aha I think I figured out the issue, I have two different remotes and I pushed the tags to my fork, not the main repo. You need `cargo release --push-remote <remote-name>`

**Comment by stefano-garzarella** [comment]
@chris-oo thanks!
